# Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

import fnmatch
from dataclasses import dataclass, field
from typing import Callable, Optional, Tuple, Union

import torch

from ..utils import is_te_min_version


@dataclass(frozen=True)
class ParamPredicate:
    """Wraps a matching function to make it hashable for ParamKey.
    Example:
        >>> shape_1_param = ParamPredicate(name="s1", fn=lambda param: len(param.shape) == 1)
        >>> shape_1_param(torch.empty(10))
        True
        >>> shape_1_param_copy = ParamPredicate(name="s1", fn=lambda param: len(param.shape) == 1)
        >>> shape_1_param == shape_1_param_copy  # name is used to match
        True
        >>> {shape_1_param, shape_1_param_copy} == {shape_1_param}  # set hashing works properly

    NOTE:
        __hash__ and __eq__ are automatically generated by @dataclass(frozen=True)
        based solely on 'name' because we set compare=False/hash=False on 'fn'.
    """

    name: str
    fn: Callable[[torch.nn.Parameter], bool] = field(compare=False, hash=False)

    def __call__(self, param: torch.nn.Parameter) -> bool:
        return self.fn(param)


@dataclass(frozen=True)
class ParamWithNamePredicate:
    """Wraps a matching function to make it hashable for ParamKey.
    Example:
        >>> shape_1_not_qkln_param = ParamWithNamePredicate(
                name="s1_not_qkln",
                fn=lambda param, name: (
                    len(param.shape) == 1 or name.endswith(".bias")
                    and not ("q_layernorm." in name or "k_layernorm." in name)
                )
            )
        >>> shape_1_not_qkln_param(torch.empty(10), "interesting.bias")
        True
        >>> shape_1_not_qkln_param(torch.empty(10), "interesting.q_layernorm.bias")
        False

    NOTE:
        __hash__ and __eq__ are automatically generated by @dataclass(frozen=True)
        based solely on 'name' because we set compare=False/hash=False on 'fn'.
    """

    name: str
    fn: Callable[[torch.nn.Parameter, str], bool] = field(compare=False, hash=False)

    def __call__(self, param: torch.nn.Parameter, name: str) -> bool:
        return self.fn(param, name)


@dataclass(frozen=True, slots=True)
class ParamKey:
    """Key to group parameters by. All such grouped parameters can share an
    optimizer config specification."""

    # TODO: Can add layer_id here later.

    name: Union[str, Tuple[str]] = field(default_factory=tuple)
    """Parameter name(s), will use unix filesystem path syntax for matching."""

    attr: Union[str, Tuple[str]] = field(default_factory=tuple)
    """Parameter attribute(s)."""

    predicate: Union[ParamPredicate, Tuple[ParamPredicate]] = field(default_factory=tuple)
    """Predicate(s) to match parameters by. If multiple predicates are provided, any must match."""

    with_name_predicate: Union[ParamWithNamePredicate, Tuple[ParamWithNamePredicate]] = field(
        default_factory=tuple
    )
    """
    Predicate(s) to match parameters with their name. If multiple predicates are provided, 
      any must match. This is useful if you need to filter out some parameters from an otherwise 
      positive match by their name.
    """

    def matches(self, param: torch.nn.Parameter, param_name: str) -> bool:
        """Returns true if passed-in parameter (with name) matches `param_key`.

        Args:
            param (torch.nn.Parameter): Handle to parameter object.
            param_name (str): Name of parameter in underlying PyTorch module.

        Returns:
            bool: True if parameter matches passed-in param_key.
        """

        # Check if name matches.
        if isinstance(self.name, str):
            target_names = [self.name]
        else:
            target_names = list(self.name)
        for target_name in target_names:
            if fnmatch.fnmatch(param_name, target_name):
                return True

        # Check if attribute matches.
        if isinstance(self.attr, str):
            target_attrs = [self.attr]
        else:
            target_attrs = list(self.attr)
        for target_attr in target_attrs:
            if getattr(param, target_attr, False):
                return True

        # Check if predicate matches.
        if isinstance(self.predicate, ParamPredicate):
            if self.predicate(param):
                return True
        else:
            for predicate in self.predicate:
                if predicate(param):
                    return True

        # Check if with_name_predicate matches.
        if isinstance(self.with_name_predicate, ParamWithNamePredicate):
            if self.with_name_predicate(param, param_name):
                return True
        else:
            for predicate in self.with_name_predicate:
                if predicate(param, param_name):
                    return True
        return False


@dataclass
class OptimizerConfig:
    """Base optimizer configuration object."""

    ##############
    # General
    ##############

    lr: Optional[float] = None
    """Initial learning rate. Depending on decay style and initial warmup, the learning rate at each
       iteration would be different.
    """

    min_lr: Optional[float] = None
    """Minumum value for learning rate. The scheduler clip values below this threshold."""

    decoupled_lr: Optional[float] = None
    """Separate learning rate for the input and output layer."""

    decoupled_min_lr: Optional[float] = None
    """Minimum value for learning rate for the input and output layer. The scheduler clip values
       below this threshold.
    """

    weight_decay: float = 0.01
    """Weight decay coefficient for L2 regularization."""

    apply_wd_to_qk_layernorm: bool = False
    """If true, apply weight decay to qk layernorm as a special case."""

    weight_decay_all_param: bool = False
    """If true, apply weight decay to all parameters, including the scalar/1d parameters
       (e.g. biases and norm weights) that Megatron skips by default. Takes precedence over
       apply_wd_to_qk_layernorm."""

    ##############
    # Precision
    ##############
    fp8_recipe: Optional[str] = None
    """The type of fp8 recipe will affect the processing logic inside distributed optimizer."""

    fp16: bool = False
    """If true, train with fp16 mixed precision training. Defaults to False."""

    bf16: bool = False
    """If true, train with bf16 mixed precision training. Defaults to False."""

    reuse_grad_buf_for_mxfp8_param_ag: bool = False
    """If true, reuse the grad buffer for param AG when using mxfp8 recipe. Should be 
       set to True only when fp8_recipe is mxfp8 and fp8_param_gather is True."""

    params_dtype: torch.dtype = torch.float32
    """dtype used when intializing the weights. Defaults to torch.float32."""

    use_precision_aware_optimizer: bool = False
    """If true, allows optimizer-related tensors (master_param, gradients and optimizer states)
    to be set to lower precision. Defaults to False.
    """

    store_param_remainders: bool = True
    """If true, store the 16-bit FP32 parameter remainders in the optimizer state, excluding the
        16 bits shared with the BF16 parameters. This lowers GPU memory usage. Defaults to True.
    """

    main_grads_dtype: torch.dtype = torch.float32
    """dtype of main grads when enabling precision-aware-optimizer"""

    main_params_dtype: torch.dtype = torch.float32
    """dtype of main params when enabling precision-aware-optimizer"""

    exp_avg_dtype: torch.dtype = torch.float32
    """dtype of exp_avg when enabling precision-aware-optimizer"""

    exp_avg_sq_dtype: torch.dtype = torch.float32
    """dtype of exp_avg_sq when enabling precision-aware-optimizer"""

    optimizer: str = 'adam'
    """Optimizer name. NOTE: Deprecated, use individual optimizer classes instead."""

    ###############
    # Loss scaling
    ###############
    loss_scale: Optional[float] = None
    """Static loss scaling, positive power of 2 values can improve fp16 convergence. If None,
       dynamic loss scaling is used.
    """

    initial_loss_scale: float = 2**32
    """Initial loss-scale for dynamic loss scaling."""

    min_loss_scale: float = 1.0
    """Minimum loss scale for dynamic loss scaling."""

    loss_scale_window: float = 1000
    """Window over which to raise/lower dynamic scale."""

    hysteresis: int = 2
    """Hysteresis for dynamic loss scaling."""

    ###################################################################################
    # Optimizer (NOTE: Deprecated, use individual optimizer classes instead.).
    ###################################################################################
    # Adam.
    adam_beta1: float = 0.9
    """First coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_beta2: float = 0.999
    """Second coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_eps: float = 1e-08
    """Term added to the denominator to improve numerical stability in Adam optimizer."""

    decoupled_weight_decay: bool = True
    """If true, decouples weight decay from the gradient update, equivalent to AdamW. If false,
    original Adam update rule will be used. Defaults to True.
    """

    # SGD.
    sgd_momentum: float = 0.9
    """Momentum factor for SGD optimizer."""

    # Muon.
    # TODO: move muon configs to it's own `MuonConfig`.
    muon_momentum: float = 0.95
    """The momentum used by the internal SGD."""

    muon_split_qkv: bool = True
    """Whether to split QKV parameters for Muon optimizer."""

    muon_split_fc1: bool = True
    """Whether to split fused GLU FC1 parameters into gate/up matrices for Muon and
    MDDecoupling."""

    muon_split_mla_per_head: bool = False
    """Whether to split MLA up-projection parameters per attention head for Muon optimizer."""

    muon_use_nesterov: bool = False
    """Whether to use Nesterov-style momentum in the internal SGD."""

    muon_scale_mode: str = "spectral"
    """The mode to use for the scale factor. Defaults to "spectral"."""

    muon_router_scale_mode: str = "none"
    """Muon scale-factor mode for MoE router weights under md_decoupling, overriding
    ``muon_scale_mode`` for routers only. Defaults to "none" (constant 1.0): the router maps
    hidden -> num_experts, so its aspect ratio — and hence the shape-derived scale factor
    (e.g. shape_up) — tracks hidden even when the matrix LR is held fixed, which breaks LR
    transfer across width. Set to a mode name to make routers follow that scale instead."""

    muon_fp32_matmul_prec: str = "medium"
    """The precision to use for the fp32 matmul. Defaults to "medium"."""

    muon_coefficient_type: str = "quintic"
    """Newton-Schulz coefficient type for the Muon optimizer. Valid types are discovered
    dynamically from the installed ``emerging_optimizers`` package. Defaults to "quintic"."""

    muon_num_ns_steps: int = 5
    """The number of iteration steps to use in the Newton-Schulz iteration."""

    muon_tp_mode: str = "duplicated"
    """How to perform NS calculation for tensor parallel weights. Defaults to "duplicated", which
    orthogonalizes the full (TP-unsharded) matrix; "blockwise" treats each shard as its own matrix,
    which is incompatible with hypersphere_radius_mode='fan_in'."""

    muon_extra_scale_factor: float = 1.0
    """Additional scale factor for the muon update."""

    muon_scalar_optimizer: str = 'adam'
    """Optimizer for nonlinear parameters (embeddings, biases, norms) when using muon.
    One of 'adam' or 'lion'. Defaults to 'adam'."""

    ###################################################################################
    # Neutrino (communication-efficient Muon): projects the momentum matrix onto a thin
    # k-dimensional random basis regenerated locally from a shared seed before any
    # communication happens, exchanges only the thin projection, and preserves the
    # unprojected residual as error feedback. Reuses matrix_lr / muon_momentum /
    # muon_use_nesterov / muon_scale_mode / min_lr_mode from the Muon/MDDecoupling fields
    # above; see megatron/core/optimizer/neutrino.py for the full algorithm.
    ###################################################################################
    neutrino_k: int = 512
    """Random basis rank k (used when neutrino_k_mode == 'fixed'). Falls back to full-rank
    Newton-Schulz (bit-identical to Muon) whenever k >= min(M, N) for a given matrix."""

    neutrino_k_mode: str = 'fixed'
    """'fixed' uses neutrino_k directly; 'ratio' sets k = round(neutrino_k_ratio * min(M, N))
    per parameter shape."""

    neutrino_k_ratio: float = 0.25
    """Effective-rank ratio used when neutrino_k_mode == 'ratio'."""

    neutrino_basis_init: str = 'gaussian'
    """Random basis distribution: 'gaussian' (default), 'rademacher', 'uniform', or
    'orthonormal' (Haar-random via QR)."""

    neutrino_orth_mode: str = 'cholesky_qr'
    """Orthonormalization of the thin projection Y. 'cholesky_qr' (default) is the
    historical path: U = Y L^-T, the QR factor, whose update alignment is tr(R) with
    R = L^T. 'polar' right-multiplies by the exact k*k polar factor of R so the update
    attains ||R||_*, the true subspace-restricted spectral LMO value. The gap is
    (tr(R)/||R||_*)^2 in guaranteed per-step decrease and is scale-invariant, so no
    learning rate or scale mode can absorb it."""

    neutrino_no_momentum: bool = False
    """Skip allocating the momentum buffer (memory saving; use raw gradients instead)."""

    neutrino_sketch_side: str = 'short'
    """'short' (default) sketches the input side, Y = G V with V N x k, so the wire tensor
    is M x k. 'long' transposes any matrix with M > N before sketching so the sketched
    dimension is always max(M, N) and the wire tensor is min(M, N) x k."""

    neutrino_k_long: Optional[int] = None
    """Rank used instead of neutrino_k on exactly the matrices the 'long' path transposes
    (the equal-bytes ablation, k' = k * max(M, N) / min(M, N)). Requires 'long'."""

    neutrino_basis_refresh: int = 1
    """Basis refresh period T: the sketch seed uses step // T, so one random basis V is
    reused for T consecutive steps. 1 (default) draws a fresh basis every step; 0 fixes one
    subspace for the whole run."""

    neutrino_overlap_lags: Optional[Tuple[int, ...]] = None
    """Diagnostic only: lags h at which to log neutrino/overlap_lag{h}, the mean subspace
    overlap between the current basis V_t and V_{t-h} (regenerated from its seed), on the
    neutrino_metrics_interval cadence."""

    neutrino_no_error_feedback: bool = False
    """Disable error feedback (drop the off-subspace residual instead of folding it back into
    the next step). Empirically beneficial at low compression ratios in our own sweeps —
    do not assume the intuitive crossover point without re-testing."""

    neutrino_scale_mode: Optional[str] = None
    """Muon scale_mode string for Neutrino's OWN compressed-branch reconstruction
    (currently consumed by NeutrinoMD; distinct from --muon-scale-mode, which
    drives MuonMD's/Muon's full-rank Newton-Schulz branch). None lets the
    consumer pick its own Neutrino-appropriate default (NeutrinoMD defaults to
    'rank_correct_calibrated') rather than silently inheriting whatever
    muon_scale_mode happens to be tuned to for a DIFFERENT scale-factor
    function with no rank-correction term -- conflating the two caused a
    silent ~2x under-scaling of NeutrinoMD's compressed branch in the first
    real-sweep pass (see variant-ablation-report.md §6)."""

    neutrino_metrics_interval: int = 50
    """Log diagnostic metrics (error/update/orthogonality ratios, comm-savings) every N steps.
    0 disables. Diagnostics are accumulated on-device with a single host sync at log time."""

    neutrino_dp_projection: bool = False

    neutrino_dp_wire_bf16: bool = False
    """Send the thin Y in bf16 rather than fp32. Y is built in fp32 because Cholesky-QR
    on the k x k Gram is ill-conditioned in bf16, but that constrains the FACTORIZATION,
    not the transport. The dense gradient this exchange replaces is bf16 in Megatron's
    grad buffer, so fp32-on-the-wire moves twice the bytes of the thing it stands in for.
    Halves realized DP traffic; default False preserves prior behaviour."""
    """Replace Megatron's dense data-parallel gradient all-reduce with an all-reduce of the
    thin projected Y for Neutrino-managed params — this is the actual communication-saving
    path (without it, DDP still all-reduces the dense gradient regardless of k). Requires the
    replicated (non-layer-wise) all-reduce DP path: do NOT combine with
    --use-layer-wise-distributed-optimizer, and pass --clip-grad 0.0."""

    neutrino_log_subspace_drift: bool = False
    """Diagnostic only, no effect on the update: log the subspace overlap between this step's
    and the previous step's orthonormalized U (the realized thin projection) for every
    low-rank-compressed bucket, alongside the analytically-expected overlap for two
    independent random k-dim subspaces of R^M (k_eff / M). Tests whether Neutrino's realized
    subspace drifts slower than chance despite the basis V being freshly random every step —
    the premise a PowerSGD-style warm-started basis would need to hold before it's worth the
    added communication (see researchtools/scratchpad/neutrino-scratch/
    brainstorm-neutrino-improvements.md, section 4)."""

    neutrino_subspace_drift_interval: int = 50
    """Host-sync cadence (in steps) for --neutrino-log-subspace-drift. The overlap itself is
    computed every step (cheap: one extra batched matmul+trace on already-computed U, no new
    device syncs); this only controls how often the buffered per-step values are flushed to
    wandb in a single sync, mirroring neutrino_metrics_interval's gating rationale."""

    ###################################################################################
    # Neutrino algorithmic variants (see _research/variants/neutrino_variants.py and
    # researchtools/scratchpad/neutrino-scratch/brainstorm-neutrino-improvements.md §2 /
    # powersgd-muon-hybrid-design.md). 'base' (default) is the unmodified Neutrino class
    # above; any other value selects a Neutrino subclass from _research/variants/'s
    # VARIANT_REGISTRY, resolved lazily so this file has no load-time dependency on
    # _research/ being on PYTHONPATH (falls back to 'base' with a warning if not found).
    ###################################################################################
    neutrino_variant: str = 'base'
    """'base' | 'srht' | 'ef21' | 'kschedule' | 'perlayerk' | 'powersgd'. See
    _research/variants/neutrino_variants.py for what each does."""

    neutrino_k_schedule_start_k: Optional[int] = None
    """neutrino_variant=kschedule only: k at step 0. None uses the class default (32)."""

    neutrino_k_schedule_end_k: Optional[int] = None
    """neutrino_variant=kschedule only: k once the schedule finishes ramping. None uses the
    class default (256)."""

    neutrino_k_schedule_total_steps: Optional[int] = None
    """neutrino_variant=kschedule only: steps over which k ramps from start to end (then
    holds at end_k). None uses the class default (2000)."""

    neutrino_k_schedule_style: Optional[str] = None
    """neutrino_variant=kschedule only: 'linear' or 'cosine'. None uses the class default
    ('linear')."""

    neutrino_layer_k_overrides: Optional[str] = None
    """neutrino_variant=perlayerk only: compact per-layer-type k spec, e.g.
    'attention=512,mlp=128'. Layer type is inferred from param name substring
    ('self_attention'/'attention' -> 'attention', 'mlp'/'linear_fc' -> 'mlp') at optimizer
    construction time; anything untagged falls back to the global neutrino_k/k_ratio."""

    neutrino_ef_variant: Optional[str] = None
    """neutrino_variant=ef21 only: reserved for future EF21 sub-variants; currently unused
    (NeutrinoEF21's behavior is fixed) but threaded through for forward compatibility."""

    ###################################################################################
    # Dion: a warm-started, power-iterated low-rank orthonormalized update (arXiv:2504.05295).
    # Unlike Neutrino's fresh-random-basis-per-step design, Dion maintains a persistent basis Q
    # refined by one power-iteration step per training step, giving a higher-fidelity subspace
    # per rank at the cost of Q being real optimizer state. Reuses matrix_lr / min_lr_mode from
    # the Muon/MDDecoupling fields above. See megatron/core/optimizer/dion.py.
    ###################################################################################
    dion_mu: float = 0.95
    """Error-feedback retention factor: after projecting, the momentum buffer is reduced by
    (1 - dion_mu) times the reconstructed low-rank part each step."""

    dion_rank: int = 256
    """Low-rank basis dimension (clamped to min(M, N) per parameter shape)."""

    dion_eps: float = 1e-8
    """Numerical epsilon for the column-normalization step when refreshing the basis."""

    dion_dp_projection: bool = False
    """Reserved for symmetry with --neutrino-dp-projection; not yet wired to a DDP-level skip
    hook in this tree, so leaving this False is always safe (just not communication-optimal)."""

    # Lion.
    lion_beta1: float = 0.95
    """First beta coefficient for Lion optimizer (used in sign update). Defaults to 0.95."""

    lion_beta2: float = 0.98
    """Second beta coefficient for Lion optimizer (used in momentum EMA update).
    Defaults to 0.98."""

    ###################################################################################
    # MDDecoupling (magnitude-direction decoupling: hypersphere normalization + learnable
    # per-axis gains + optional Muon orthogonalized updates). Reuses the muon_* / adam_* /
    # weight_decay fields above for shared knobs.
    ###################################################################################
    matrix_lr: Optional[float] = None
    """Absolute LR for matrix (2D non-embedding/output) params under --optimizer md_decoupling or
    muon/dist_muon (the Muon-managed matrices; the scalar Adam/Lion group stays on --lr).
    Overrides muon_lr_factor * lr."""

    embedding_lr_multiplier: Optional[float] = None
    """LR multiplier for embedding (and tied LM-head) params under md_decoupling. Final
    max_lr = embedding_lr_multiplier * lr. When unset, those params use the base --lr."""

    output_lr: Optional[float] = None
    """Absolute LR for the (untied) output LM-head params under md_decoupling. When unset, the
    output layer uses the base --lr."""

    min_lr_mode: str = 'relative'
    """How per-group min_lr is set for any group with a custom max_lr. 'relative' (default):
    every group decays by the same fraction (config.min_lr / config.lr). 'absolute': every group
    decays to the same floor (config.min_lr)."""

    muon_lr_factor: float = 1.0
    """When --matrix-lr is unset, matrix-param LR for md_decoupling and muon/dist_muon is
    muon_lr_factor * lr. Default 1.0 (matrices track the base --lr)."""

    hypersphere_mode: Optional[str] = 'flat'
    """Hypersphere normalization mode for non-embedding/output 2D matrices. One of
    'row'/'col'/'flat'/'embed'/'none'. Applied post-step to project the weight onto the L2 sphere.
    None = off."""

    hypersphere_embedding_mode: Optional[str] = 'row'
    """Hypersphere mode override for embedding + LM head. One of
    'row'/'col'/'flat'/'embed'/'none'/'external'. 'external' routes those params to the chained
    optimizer; 'none' keeps them in MDDecoupling without post-step normalization."""

    hypersphere_router_mode: Optional[str] = 'row'
    """Hypersphere mode override for MoE router weights. One of 'row'/'col'/'flat'/'embed'/'none'.
    None disables router-specific normalization."""

    hypersphere_tangential_grad: bool = False
    """Project p.grad onto the hypersphere tangent space before the update."""

    hypersphere_preserve_init: bool = False
    """Skip init-time hypersphere projection so the model init magnitude survives into training.
    When gains are configured (single-axis), gains absorb the per-axis init magnitude."""

    hypersphere_scale_out_proj_init: bool = True
    """Scale the hypersphere target radius for is_out_proj params (linear_proj, linear_fc2) by
    1/sqrt(2 * num_layers), matching scaled_init_method_normal."""

    hypersphere_radius_mode: str = 'shape_native'
    """Where to place the hypersphere, relative to the shape-native radius (unit row/col slices,
    sqrt(max(d_out,d_in)) for flat). One of 'shape_native'/'init'/'fan_in'.
    'init': flat-mode sphere at the matrix's init Frobenius norm (assumes init_std=1/sqrt(hidden)),
    rescaling both the projection target and the Muon update by sqrt(min(d_out,d_in)/hidden) so
    narrow matrices (MLA lora, MoE fc2, GQA K/V) stay on their init sphere.
    'fan_in': sphere at init_std=1/sqrt(d_in), i.e. ||W||_F = sqrt(d_out) (unit rows) for any shape
    and both the 'row' and 'flat' sphere modes, with the Muon update rescaled to match. Independent
    of hidden_size, so it also holds for blocks whose axes are both off the residual stream."""

    md_router_use_orthogonal_updates: Optional[bool] = True
    """Per-param-group override for use_orthogonal_updates on MoE router weights. True forces
    Muon for routers, False forces the Adam branch, None follows --use-orthogonal-updates."""

    use_orthogonal_updates: bool = True
    """Use Muon-style orthogonalized updates for matrix params under md_decoupling. Embedding +
    LM head ALWAYS use the Adam branch regardless of this flag."""

    md_normalize_update_to_weight_norm: bool = False
    """If true, rescale each existing logical MuonMD update block ``U`` to
    ``U / ||U||_F * R_W``. This measures the actual update norm instead of assuming an ideal
    semi-orthogonal norm of ``sqrt(min(d_out, d_in))``. Each corresponding weight-block norm
    ``R_W`` is measured once before the first update and cached. Muon scale modes and other
    scalar update factors are superseded for this path."""

    hypersphere_gains_mode: Optional[str] = 'rowcol'
    """Learnable per-axis gains for matrix params. One of
    'row'/'col'/'rowcol'/'flat'/'embed'/'none'."""

    hypersphere_gains_mode_output: Optional[str] = 'inherit'
    """Gains mode override for the LM head. One of
    'row'/'col'/'rowcol'/'flat'/'inherit'/'none'. 'inherit' uses the base gains mode."""

    hypersphere_gains_mode_embedding: Optional[str] = 'none'
    """Gains mode override for the embedding. One of
    'row'/'col'/'rowcol'/'flat'/'inherit'/'none'. None or 'inherit' uses the base gains mode."""

    hypersphere_gains_mode_router: Optional[str] = 'rowcol'
    """Gains mode override for MoE router weights. One of
    'row'/'col'/'rowcol'/'flat'/'inherit'/'none'. None or 'inherit' uses the base gains mode.
    Defaults to 'rowcol'. Only takes effect when --hypersphere-gains-mode is set (routers otherwise
    have no gains at all)."""

    gains_lr: Optional[float] = None
    """Absolute LR for the per-axis gains AdamW. When unset, falls back to --lr (and still tracks
    the schedule shape of the main LR)."""

    gain_parametrization: str = 'softplus'
    """Reparametrize the stored gain g; effective multiplier is phi(g). 'direct' keeps phi(g)=g;
    'softplus' uses phi(g)=softplus(g) (always positive). Applied uniformly to row/col/flat."""

    gains_no_clamp_min: bool = False
    """Drop the 1e-8 clamp_min on phi(g) when recovering the bare weight in _preprocess_gains.
    The clamp floors the divisor, which is asymmetric with _apply_gains (multiplies by the true,
    unclamped phi(g)) and — under gain_parametrization='direct' — blocks a gain from shrinking
    through 1e-8 or flipping sign. Setting this makes the recover/apply round-trip exact for any
    nonzero gain, letting direct gains go small or negative. No-op for 'softplus' (phi(g)>0)."""

    use_layer_wise_distributed_optimizer: bool = False
    """If true, wrap the optimizer with LayerWiseDistributedOptimizer to shard optimizer state
    over the data-parallel group (used by md_decoupling instead of the standard distributed
    optimizer, which is incompatible with 2D hypersphere/Muon math)."""

    #######################
    # Distributed optimizer
    #######################
    use_distributed_optimizer: bool = False
    """Distribute optimizer state over data-parallel replicas."""

    overlap_param_gather: bool = False
    """If true, overlap param all-gather with forward compute. 
        This argument is intended to have the same value as the "overlap_param_gather" argument 
        in the "distributed_data_parallel_config.py" file. In the optimizer, this argument is 
        only used when "reuse_grad_buf_for_mxfp8_param_ag=True & fp8_param_gather=True".
    """

    overlap_param_gather_with_optimizer_step: bool = False
    """If true, overlap param all-gather of first bucket with optimizer step."""

    #######################
    # Optimizer Offload
    #######################

    optimizer_cpu_offload: bool = False
    """If True, offload optimizer states tensor and compute to CPU."""

    optimizer_offload_fraction: float = 0.0
    """Specifies the fraction of optimizer states to offload from GPU memory to CPU."""

    use_torch_optimizer_for_cpu_offload: bool = False
    """If True, use torch.optim.Optimizer for CPU offload."""

    overlap_cpu_optimizer_d2h_h2d: bool = False
    """
    When set to `True`, this flag enables overlapping of the CPU optimizer
    update process with the data transfer operations. This can help improve
    overall training efficiency by reducing idle time during data movement,
    allowing the optimizer to perform updates while gradients and parameters
    are being transferred between devices.
    """

    pin_cpu_grads: bool = True
    """If True, pin the optimizer gradients to CPU memory."""

    pin_cpu_params: bool = True
    """If True, pin the optimizer parameters to CPU memory."""

    ################
    # Miscellaneous
    ################
    clip_grad: float = 1.0
    """Gradient clipping based on global L2 norm."""

    log_num_zeros_in_grad: bool = False
    """If true, calculate and log the number of zeros in gradient."""

    barrier_with_L1_time: bool = False
    """If true, use barrier with level 1 time measurements."""

    timers: Optional[Callable] = None
    """Function to get timers."""

    config_logger_dir: str = ""
    """When non-empty, dumps entry-point configs to config_logger_dir"""

    optimizer_cuda_graph: bool = False
    """If true, enables CUDA graph for optimizer step."""

    def __post_init__(self):
        """Check the validity of the config."""

        # The following condition is used to avoid repetition in distrib_optimizer.py.
        # This is because in distrib_optimizer.py, the process to handle parameters are
        # different for different training precision settings. FP8 cases require different
        # handling while FP8 delayed scaling is an exception because the Adam optimizer in
        # TransformerEngine supports it in the kernel computation.
        # This is also the flag to determine the usage of param.grad or param.decoupled_grad
        self.use_precision_aware_optimizer_no_fp8_or_ds_fp8 = (
            self.use_precision_aware_optimizer
            and (
                self.main_params_dtype != torch.float32
                or (self.fp8_recipe is None or self.fp8_recipe == "delayed")
                or self.optimizer_cpu_offload
            )
        )

        if self.fp8_recipe == "mxfp8":
            if not self.reuse_grad_buf_for_mxfp8_param_ag:
                import warnings

                warnings.warn(
                    "mxfp8 without using reuse_grad_buf_for_mxfp8_param_ag and fp8_param_gather"
                    "will use significant amount additional GPU memory."
                    "Setting --reuse-grad-buf-for-mxfp8-param-ag and --fp8-param-gather is "
                    "recommended for mxfp8 training."
                )

        if self.use_precision_aware_optimizer:
            assert (
                self.optimizer == 'adam'
            ), '--use-precision-aware-optimizer only supported with adam'
            assert (
                self.use_distributed_optimizer
            ), '--use-precision-aware-optimizer only supported with distributed optimizer'

            if not is_te_min_version("2.1.0"):
                self.store_param_remainders = False

            # Only the FusedAdam in TE and HybridDeviceOptimizer supports
            # --use-precision-aware-optimizer.
            # TODO: Remove this check when apex's FusedAdam is no longer used.
            if self.optimizer_cpu_offload:
                return
            try:
                import inspect

                # TODO: Move this below?
                from transformer_engine.pytorch.optimizers import FusedAdam as Adam

                adam_args = inspect.signature(Adam).parameters
                arg_names = [
                    'master_weight_dtype',
                    'exp_avg_dtype',
                    'exp_avg_sq_dtype',
                    'use_decoupled_grad',
                ]
                for name in arg_names:
                    assert name in adam_args, (
                        "Current FusedAdam of TE doesn't support --use-precision-aware-optimizer, "
                        "please update TE version."
                    )
            except ImportError:
                raise RuntimeError(
                    '--use-precision-aware-optimizer requires FusedAdam from TransformerEngine, '
                    'but not found.'
                )
        else:
            assert (
                self.main_grads_dtype == torch.float32
            ), "main_grads_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.main_params_dtype == torch.float32
            ), "main_params_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.exp_avg_dtype == torch.float32
            ), "exp_avg_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.exp_avg_sq_dtype == torch.float32
            ), "exp_avg_sq_dtype can only be fp32 when not using precision-aware optimizer"


@dataclass
class AdamOptimizerConfig(OptimizerConfig):
    """Adam optimizer configuration object."""

    optimizer: str = 'adam'
    """Optimizer name."""

    adam_beta1: float = 0.9
    """First coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_beta2: float = 0.999
    """Second coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_eps: float = 1e-08
    """Term added to the denominator to improve numerical stability in Adam optimizer."""


@dataclass
class SGDOptimizerConfig(OptimizerConfig):
    """SGD optimizer configuration object."""

    optimizer: str = 'sgd'
    """Optimizer name."""

    sgd_momentum: float = 0.9
    """Momentum factor for SGD optimizer."""
